version: 1.1.0
use_sim: true # is this a simulated environment

#TASKS
active_tasks: # list of tasks active in the simulation
  - transportation
  #- picking
  #- uv_treatment
max_load_duration: 60 # timeout for how long the robot should wait to be loaded at the picker
max_unload_duration: 10 # timeout for how long the robot should wait to be loaded at the picker

#TOPOLOGY
base_station_nodes_pool: &base_stations_nodes_pool # potential base station locations
  - WayPoint22
  - WayPoint24
wait_nodes_pool: *base_stations_nodes_pool # potential idle locations

charging_station_nodes: # node the robots can use to charge their batteries
  - WayPoint24

local_storage_nodes: # node to collate the picked fruit
  - WayPoint23

use_cold_storage: false # is cold storage active
cold_storage_node: None # node to deposit the collated fruit

#ROUTING
planning_type: fragment_planner # method used for coordinating routes

#ROBOTS
admissible_robot_ids: # robots allowed to register with simulation
  - thorvald_001
  - thorvald_002
  - thorvald_003
  - thorvald_004
  - thorvald_005
  - thorvald_006
  - thorvald_007
  - thorvald_008
  - thorvald_009
  - thorvald_010
  - thorvald_011
  - thorvald_012
  - thorvald_013
  - thorvald_014
  - thorvald_015
  - thorvald_016
  - thorvald_017
  - thorvald_018
  - thorvald_019
low_battery_voltage: 45.0 # battery_voltage threshold to set robot as unhealthy

#PICKERS
picker_ids: # valid picker ids within the simulation
  - picker01
  - picker02
  - picker03
  - picker04
  - picker05
  - picker06
  - picker07
  - picker08
  - picker09
  - picker10
virtual_picker_ids: # valid virtual picker ids within the simulation
  - picker101
  - picker102
  - picker103
  - picker104
  - picker105
  - picker106
  - picker107
  - picker108
  - picker109
  - picker110

#INITIALISATION
spawn_list:  # robots to initialise when simulation started
  - default: null  #REQUIRED
  - robot_id: thorvald_003
    base_station_node: Waypoint22
  - robot_id: thorvald_005
    base_station_node: Waypoint24