base_station_nodes: &id_base_stations
  - WayPoint22
  - WayPoint24
wait_nodes: *id_base_stations
local_storage_node: WayPoint23
charging_station_node: WayPoint24
robot_ids: 
  - thorvald_003
  - thorvald_005
max_task_priorities: 
  - 255
  - 255
picker_ids:
  - picker01
  - picker02
  - picker03
  - picker04
  - picker05
  - picker06
  - picker07
  - picker08
  - picker09
  - picker10
virtual_picker_ids:
  - picker101
  - picker102
  - picker103
  - picker104
  - picker105
  - picker106
  - picker107
  - picker108
  - picker109
  - picker110
# is this a simulated environment
use_sim: true
# if batter_voltage is below the given threshold, the robot is set as unfit. ignored for sim
low_battery_voltage: 45.0
