modules:
  - name: base
    role: virtual_robot
  - name: health_monitoring
    role: robot
  - name: uv_treatment
    role: phototherapist
  - name: data_collection
    role: scanner
navigation_properties:
    restrictions: intra-row
    has_presence: true
visualisation_properties:
    structure_type: tall
    rviz_model: tall_robot
